// Sample extension data
const extensionsData = [
    {
        id: 1,
        name: "AdBlock Plus",
        version: "3.14.2",
        description: "Block ads and pop-ups for a cleaner browsing experience",
        status: "active",
        category: "Privacy & Security",
        icon: "🛡️",
        lastUpdated: "2024-01-15",
        size: "2.1 MB",
        rating: 4.5,
        downloads: "10M+"
    },
    {
        id: 2,
        name: "Grammarly",
        version: "8.1.0",
        description: "Check your grammar and improve your writing in real-time",
        status: "active",
        category: "Productivity",
        icon: "✍️",
        lastUpdated: "2024-01-10",
        size: "5.3 MB",
        rating: 4.8,
        downloads: "50M+"
    },
    {
        id: 3,
        name: "Dark Reader",
        version: "4.9.58",
        description: "Dark mode for every website. Automatically generates dark themes",
        status: "inactive",
        category: "Accessibility",
        icon: "🌙",
        lastUpdated: "2024-01-08",
        size: "1.8 MB",
        rating: 4.6,
        downloads: "5M+"
    },
    {
        id: 4,
        name: "LastPass",
        version: "4.85.0",
        description: "Secure password manager that keeps your passwords safe",
        status: "active",
        category: "Privacy & Security",
        icon: "🔐",
        lastUpdated: "2024-01-12",
        size: "3.2 MB",
        rating: 4.3,
        downloads: "20M+"
    },
    {
        id: 5,
        name: "Pocket",
        version: "7.0.0",
        description: "Save articles, videos, and stories to read later",
        status: "inactive",
        category: "Productivity",
        icon: "📱",
        lastUpdated: "2024-01-05",
        size: "2.7 MB",
        rating: 4.4,
        downloads: "15M+"
    },
    {
        id: 6,
        name: "uBlock Origin",
        version: "1.54.0",
        description: "An efficient blocker for Chromium-based browsers",
        status: "active",
        category: "Privacy & Security",
        icon: "🚫",
        lastUpdated: "2024-01-14",
        size: "1.5 MB",
        rating: 4.7,
        downloads: "25M+"
    },
    {
        id: 7,
        name: "Momentum",
        version: "2.0.1",
        description: "Replace new tab page with a personal dashboard",
        status: "active",
        category: "Productivity",
        icon: "⚡",
        lastUpdated: "2024-01-11",
        size: "4.1 MB",
        rating: 4.2,
        downloads: "8M+"
    },
    {
        id: 8,
        name: "ColorZilla",
        version: "2.0.2",
        description: "Advanced color picker, eyedropper, and color analyzer",
        status: "inactive",
        category: "Developer Tools",
        icon: "🎨",
        lastUpdated: "2024-01-03",
        size: "1.2 MB",
        rating: 4.1,
        downloads: "2M+"
    },
    {
        id: 9,
        name: "Honey",
        version: "17.0.0",
        description: "Automatically find and apply coupon codes at checkout",
        status: "active",
        category: "Shopping",
        icon: "🍯",
        lastUpdated: "2024-01-13",
        size: "3.8 MB",
        rating: 4.0,
        downloads: "30M+"
    },
    {
        id: 10,
        name: "Stylus",
        version: "1.5.23",
        description: "Redefine the web! Use custom styles for any website",
        status: "inactive",
        category: "Customization",
        icon: "🎭",
        lastUpdated: "2024-01-07",
        size: "2.3 MB",
        rating: 4.4,
        downloads: "3M+"
    }
];
